module NAICS exposing (NAIC, naics)
import Random exposing (Generator, int, list, minInt, maxInt)

type alias NAIC =
        { code : Int
        , title : String
        }


naics : List NAIC
naics =
                [ NAIC 111110 "Soybean Farming" 
                , NAIC 111120 "Oilseed (except Soybean) Farming"
                , NAIC 111130 "Dry Pea and Bean Farming" 
                , NAIC 111140 "Wheat Farming"
                , NAIC 111150 "Corn Farming"
                , NAIC 111160 "Rice Farming"
                , NAIC 111191 "Oilseed and Grain Combination Farming"
                , NAIC 111199 "All Other Grain Farming"
                , NAIC 111211 "Potato Farming"
                , NAIC 111219 "Other Vegetable (except Potato) and Melon Farming"
                , NAIC 111310 "Orange Groves"
                , NAIC 111320 "Citrus (except Orange) Groves"
                , NAIC 111331 "Apple Orchards"
                , NAIC 111332 "Grape Vineyards"
                , NAIC 111333 "Strawberry Farming"
                , NAIC 111334 "Berry (except Strawberry) Farming"
                , NAIC 111335 "Tree Nut Farming"
                , NAIC 111336 "Fruit and Tree Nut Combination Farming"
                , NAIC 111339 "Other Noncitrus Fruit Farming"
                , NAIC 111411 "Mushroom Production"
                , NAIC 111419 "Other Food Crops Grown Under Cover"
                , NAIC 111421 "Nursery and Tree Production"
                , NAIC 111422 "Floriculture Production"
                , NAIC 111910 "Tobacco Farming"
                , NAIC 111920 "Cotton Farming"
                , NAIC 111930 "Sugarcane Farming"
                , NAIC 111940 "Hay Farming"
                , NAIC 111991 "Sugar Beet Farming"
                , NAIC 111992 "Peanut Farming"
                , NAIC 111998 "All Other Miscellaneous Crop Farming"
                , NAIC 112111 "Beef Cattle Ranching and Farming"
                , NAIC 112112 "Cattle Feedlots"
                , NAIC 112120 "Dairy Cattle and Milk Production"
                , NAIC 112130 "Dual-Purpose Cattle Ranching and Farming"
                , NAIC 112210 "Hog and Pig Farming"
                , NAIC 112310 "Chicken Egg Production"
                , NAIC 112320 "Broilers and Other Meat Type Chicken Production"
                , NAIC 112330 "Turkey Production"
                , NAIC 112340 "Poultry Hatcheries"
                , NAIC 112390 "Other Poultry Production"
                , NAIC 112410 "Sheep Farming"
                , NAIC 112420 "Goat Farming"
                , NAIC 112511 "Finfish Farming and Fish Hatcheries"
                , NAIC 112512 "Shellfish Farming"
                , NAIC 112519 "Other Aquaculture"
                , NAIC 112910 "Apiculture"
                , NAIC 112920 "Horses and Other Equine Production"
                , NAIC 112930 "Fur-Bearing Animal and Rabbit Production"
                , NAIC 112990 "All Other Animal Production"
                , NAIC 113110 "Timber Tract Operations"
                , NAIC 113210 "Forest Nurseries and Gathering of Forest Products"
                , NAIC 113310 "Logging"
                , NAIC 114111 "Finfish Fishing"
                , NAIC 114112 "Shellfish Fishing"
                , NAIC 114119 "Other Marine Fishing"
                , NAIC 114210 "Hunting and Trapping"
                , NAIC 115111 "Cotton Ginning"
                , NAIC 115112 "Soil Preparation, Planting, and Cultivating"
                , NAIC 115113 "Crop Harvesting, Primarily by Machine"
                , NAIC 115114 "Postharvest Crop Activities (except Cotton Ginning)"
                , NAIC 115115 "Farm Labor Contractors and Crew Leaders"
                , NAIC 115116 "Farm Management Services"
                , NAIC 115210 "Support Activities for Animal Production"
                , NAIC 115310 "Support Activities for Forestry"
                , NAIC 211111 "Crude Petroleum and Natural Gas Extraction"
                , NAIC 211112 "Natural Gas Liquid Extraction"
                , NAIC 212111 "Bituminous Coal and Lignite Surface Mining"
                , NAIC 212112 "Bituminous Coal Underground Mining"
                , NAIC 212113 "Anthracite Mining"
                , NAIC 212210 "Iron Ore Mining"
                , NAIC 212221 "Gold Ore Mining"
                , NAIC 212222 "Silver Ore Mining"
                , NAIC 212231 "Lead Ore and Zinc Ore Mining"
                , NAIC 212234 "Copper Ore and Nickel Ore Mining"
                , NAIC 212291 "Uranium-Radium-Vanadium Ore Mining"
                , NAIC 212299 "All Other Metal Ore Mining"
                , NAIC 212311 "Dimension Stone Mining and Quarrying"
                , NAIC 212312 "Crushed and Broken Limestone Mining and Quarrying"
                , NAIC 212313 "Crushed and Broken Granite Mining and Quarrying"
                , NAIC 212319 "Other Crushed and Broken Stone Mining and Quarrying"
                , NAIC 212321 "Construction Sand and Gravel Mining"
                , NAIC 212322 "Industrial Sand Mining"
                , NAIC 212324 "Kaolin and Ball Clay Mining"
                , NAIC 212325 "Clay and Ceramic and Refractory Minerals Mining"
                , NAIC 212391 "Potash, Soda, and Borate Mineral Mining"
                , NAIC 212392 "Phosphate Rock Mining"
                , NAIC 212393 "Other Chemical and Fertilizer Mineral Mining"
                , NAIC 212399 "All Other Nonmetallic Mineral Mining"
                , NAIC 213111 "Drilling Oil and Gas Wells"
                , NAIC 213112 "Support Activities for Oil and Gas Operations"
                , NAIC 213113 "Support Activities for Coal Mining"
                , NAIC 213114 "Support Activities for Metal Mining"
                , NAIC 213115 "Support Activities for Nonmetallic Minerals (except Fuels) Mining"
                , NAIC 221111 "Hydroelectric Power Generation"
                , NAIC 221112 "Fossil Fuel Electric Power Generation"
                , NAIC 221113 "Nuclear Electric Power Generation"
                , NAIC 221114 "Solar Electric Power Generation"
                , NAIC 221115 "Wind Electric Power Generation"
                , NAIC 221116 "Geothermal Electric Power Generation"
                , NAIC 221117 "Biomass Electric Power Generation"
                , NAIC 221118 "Other Electric Power Generation"
                , NAIC 221121 "Electric Bulk Power Transmission and Control"
                , NAIC 221122 "Electric Power Distribution"
                , NAIC 221210 "Natural Gas Distribution"
                , NAIC 221310 "Water Supply and Irrigation Systems"
                , NAIC 221320 "Sewage Treatment Facilities"
                , NAIC 221330 "Steam and Air-Conditioning Supply"
                , NAIC 236115 "New Single-Family Housing Construction (except For-Sale Builders)"
                , NAIC 236116 "New Multifamily Housing Construction (except For-Sale Builders)"
                , NAIC 236117 "New Housing For-Sale Builders"
                , NAIC 236118 "Residential Remodelers"
                , NAIC 236210 "Industrial Building Construction"
                , NAIC 236220 "Commercial and Institutional Building Construction"
                , NAIC 237110 "Water and Sewer Line and Related Structures Construction"
                , NAIC 237120 "Oil and Gas Pipeline and Related Structures Construction"
                , NAIC 237130 "Power and Communication Line and Related Structures Construction"
                , NAIC 237210 "Land Subdivision"
                , NAIC 237310 "Highway, Street, and Bridge Construction"
                , NAIC 237990 "Other Heavy and Civil Engineering Construction"
                , NAIC 238110 "Poured Concrete Foundation and Structure Contractors"
                , NAIC 238120 "Structural Steel and Precast Concrete Contractors"
                , NAIC 238130 "Framing Contractors"
                , NAIC 238140 "Masonry Contractors"
                , NAIC 238150 "Glass and Glazing Contractors"
                , NAIC 238160 "Roofing Contractors"
                , NAIC 238170 "Siding Contractors"
                , NAIC 238190 "Other Foundation, Structure, and Building Exterior Contractors"
                , NAIC 238210 "Electrical Contractors and Other Wiring Installation Contractors"
                , NAIC 238220 "Plumbing, Heating, and Air-Conditioning Contractors"
                , NAIC 238290 "Other Building Equipment Contractors"
                , NAIC 238310 "Drywall and Insulation Contractors"
                , NAIC 238320 "Painting and Wall Covering Contractors"
                , NAIC 238330 "Flooring Contractors"
                , NAIC 238340 "Tile and Terrazzo Contractors"
                , NAIC 238350 "Finish Carpentry Contractors"
                , NAIC 238390 "Other Building Finishing Contractors"
                , NAIC 238910 "Site Preparation Contractors"
                , NAIC 238990 "All Other Specialty Trade Contractors"
                , NAIC 311111 "Dog and Cat Food Manufacturing"
                , NAIC 311119 "Other Animal Food Manufacturing"
                , NAIC 311211 "Flour Milling"
                , NAIC 311212 "Rice Milling"
                , NAIC 311213 "Malt Manufacturing"
                , NAIC 311221 "Wet Corn Milling"
                , NAIC 311224 "Soybean and Other Oilseed Processing"
                , NAIC 311225 "Fats and Oils Refining and Blending"
                , NAIC 311230 "Breakfast Cereal Manufacturing"
                , NAIC 311313 "Beet Sugar Manufacturing"
                , NAIC 311314 "Cane Sugar Manufacturing"
                , NAIC 311340 "Nonchocolate Confectionery Manufacturing"
                , NAIC 311351 "Chocolate and Confectionery Manufacturing from Cacao Beans"
                , NAIC 311352 "Confectionery Manufacturing from Purchased Chocolate"
                , NAIC 311411 "Frozen Fruit, Juice, and Vegetable Manufacturing"
                , NAIC 311412 "Frozen Specialty Food Manufacturing"
                , NAIC 311421 "Fruit and Vegetable Canning"
                , NAIC 311422 "Specialty Canning"
                , NAIC 311423 "Dried and Dehydrated Food Manufacturing"
                , NAIC 311511 "Fluid Milk Manufacturing"
                , NAIC 311512 "Creamery Butter Manufacturing"
                , NAIC 311513 "Cheese Manufacturing"
                , NAIC 311514 "Dry, Condensed, and Evaporated Dairy Product Manufacturing"
                , NAIC 311520 "Ice Cream and Frozen Dessert Manufacturing"
                , NAIC 311611 "Animal (except Poultry) Slaughtering"
                , NAIC 311612 "Meat Processed from Carcasses"
                , NAIC 311613 "Rendering and Meat Byproduct Processing"
                , NAIC 311615 "Poultry Processing"
                , NAIC 311710 "Seafood Product Preparation and Packaging"
                , NAIC 311811 "Retail Bakeries"
                , NAIC 311812 "Commercial Bakeries"
                , NAIC 311813 "Frozen Cakes, Pies, and Other Pastries Manufacturing"
                , NAIC 311821 "Cookie and Cracker Manufacturing"
                , NAIC 311824 "Dry Pasta, Dough, and Flour Mixes Manufacturing from Purchased Flour"
                , NAIC 311830 "Tortilla Manufacturing"
                , NAIC 311911 "Roasted Nuts and Peanut Butter Manufacturing"
                , NAIC 311919 "Other Snack Food Manufacturing"
                , NAIC 311920 "Coffee and Tea Manufacturing"
                , NAIC 311930 "Flavoring Syrup and Concentrate Manufacturing"
                , NAIC 311941 "Mayonnaise, Dressing, and Other Prepared Sauce Manufacturing"
                , NAIC 311942 "Spice and Extract Manufacturing"
                , NAIC 311991 "Perishable Prepared Food Manufacturing"
                , NAIC 311999 "All Other Miscellaneous Food Manufacturing"
                , NAIC 312111 "Soft Drink Manufacturing"
                , NAIC 312112 "Bottled Water Manufacturing"
                , NAIC 312113 "Ice Manufacturing"
                , NAIC 312120 "Breweries"
                , NAIC 312130 "Wineries"
                , NAIC 312140 "Distilleries"
                , NAIC 312230 "Tobacco Manufacturing"
                , NAIC 313110 "Fiber, Yarn, and Thread Mills"
                , NAIC 313210 "Broadwoven Fabric Mills"
                , NAIC 313220 "Narrow Fabric Mills and Schiffli Machine Embroidery"
                , NAIC 313230 "Nonwoven Fabric Mills"
                , NAIC 313240 "Knit Fabric Mills"
                , NAIC 313310 "Textile and Fabric Finishing Mills"
                , NAIC 313320 "Fabric Coating Mills"
                , NAIC 314110 "Carpet and Rug Mills"
                , NAIC 314120 "Curtain and Linen Mills"
                , NAIC 314910 "Textile Bag and Canvas Mills"
                , NAIC 314994 "Rope, Cordage, Twine, Tire Cord, and Tire Fabric Mills"
                , NAIC 314999 "All Other Miscellaneous Textile Product Mills"
                , NAIC 315110 "Hosiery and Sock Mills"
                , NAIC 315190 "Other Apparel Knitting Mills"
                , NAIC 315210 "Cut and Sew Apparel Contractors"
                , NAIC 315220 "Men’s and Boys’ Cut and Sew Apparel Manufacturing"
                , NAIC 315240 "Women’s, Girls’, and Infants’ Cut and Sew Apparel Manufacturing"
                , NAIC 315280 "Other Cut and Sew Apparel Manufacturing"
                , NAIC 315990 "Apparel Accessories and Other Apparel Manufacturing"
                , NAIC 316110 "Leather and Hide Tanning and Finishing"
                , NAIC 316210 "Footwear Manufacturing"
                , NAIC 316992 "Women’s Handbag and Purse Manufacturing"
                , NAIC 316998 "All Other Leather Good and Allied Product Manufacturing"
                , NAIC 321113 "Sawmills"
                , NAIC 321114 "Wood Preservation"
                , NAIC 321211 "Hardwood Veneer and Plywood Manufacturing"
                , NAIC 321212 "Softwood Veneer and Plywood Manufacturing"
                , NAIC 321213 "Engineered Wood Member (except Truss) Manufacturing"
                , NAIC 321214 "Truss Manufacturing"
                , NAIC 321219 "Reconstituted Wood Product Manufacturing"
                , NAIC 321911 "Wood Window and Door Manufacturing"
                , NAIC 321912 "Cut Stock, Resawing Lumber, and Planing"
                , NAIC 321918 "Other Millwork (including Flooring)"
                , NAIC 321920 "Wood Container and Pallet Manufacturing"
                , NAIC 321991 "Manufactured Home (Mobile Home) Manufacturing"
                , NAIC 321992 "Prefabricated Wood Building Manufacturing"
                , NAIC 321999 "All Other Miscellaneous Wood Product Manufacturing"
                , NAIC 322110 "Pulp Mills"
                , NAIC 322121 "Paper (except Newsprint) Mills"
                , NAIC 322122 "Newsprint Mills"
                , NAIC 322130 "Paperboard Mills"
                , NAIC 322211 "Corrugated and Solid Fiber Box Manufacturing"
                , NAIC 322212 "Folding Paperboard Box Manufacturing"
                , NAIC 322219 "Other Paperboard Container Manufacturing"
                , NAIC 322220 "Paper Bag and Coated and Treated Paper Manufacturing"
                , NAIC 322230 "Stationery Product Manufacturing"
                , NAIC 322291 "Sanitary Paper Product Manufacturing"
                , NAIC 322299 "All Other Converted Paper Product Manufacturing"
                , NAIC 323111 "Commercial Printing (except Screen and Books)"
                , NAIC 323113 "Commercial Screen Printing"
                , NAIC 323117 "Books Printing"
                , NAIC 323120 "Support Activities for Printing"
                , NAIC 324110 "Petroleum Refineries"
                , NAIC 324121 "Asphalt Paving Mixture and Block Manufacturing"
                , NAIC 324122 "Asphalt Shingle and Coating Materials Manufacturing"
                , NAIC 324191 "Petroleum Lubricating Oil and Grease Manufacturing"
                , NAIC 324199 "All Other Petroleum and Coal Products Manufacturing"
                , NAIC 325110 "Petrochemical Manufacturing"
                , NAIC 325120 "Industrial Gas Manufacturing"
                , NAIC 325130 "Synthetic Dye and Pigment Manufacturing"
                , NAIC 325180 "Other Basic Inorganic Chemical Manufacturing"
                , NAIC 325193 "Ethyl Alcohol Manufacturing"
                , NAIC 325194 "Cyclic Crude, Intermediate, and Gum and Wood Chemical Manufacturing"
                , NAIC 325199 "All Other Basic Organic Chemical Manufacturing"
                , NAIC 325211 "Plastics Material and Resin Manufacturing"
                , NAIC 325212 "Synthetic Rubber Manufacturing"
                , NAIC 325220 "Artificial and Synthetic Fibers and Filaments Manufacturing"
                , NAIC 325311 "Nitrogenous Fertilizer Manufacturing"
                , NAIC 325312 "Phosphatic Fertilizer Manufacturing"
                , NAIC 325314 "Fertilizer (Mixing Only) Manufacturing"
                , NAIC 325320 "Pesticide and Other Agricultural Chemical Manufacturing"
                , NAIC 325411 "Medicinal and Botanical Manufacturing"
                , NAIC 325412 "Pharmaceutical Preparation Manufacturing"
                , NAIC 325413 "In-Vitro Diagnostic Substance Manufacturing"
                , NAIC 325414 "Biological Product (except Diagnostic) Manufacturing"
                , NAIC 325510 "Paint and Coating Manufacturing"
                , NAIC 325520 "Adhesive Manufacturing"
                , NAIC 325611 "Soap and Other Detergent Manufacturing"
                , NAIC 325612 "Polish and Other Sanitation Good Manufacturing"
                , NAIC 325613 "Surface Active Agent Manufacturing"
                , NAIC 325620 "Toilet Preparation Manufacturing"
                , NAIC 325910 "Printing Ink Manufacturing"
                , NAIC 325920 "Explosives Manufacturing"
                , NAIC 325991 "Custom Compounding of Purchased Resins"
                , NAIC 325992 "Photographic Film, Paper, Plate, and Chemical Manufacturing"
                , NAIC 325998 "All Other Miscellaneous Chemical Product and Preparation Manufacturing"
                , NAIC 326111 "Plastics Bag and Pouch Manufacturing"
                , NAIC 326112 "Plastics Packaging Film and Sheet (including Laminated) Manufacturing"
                , NAIC 326113 "Unlaminated Plastics Film and Sheet (except Packaging) Manufacturing"
                , NAIC 326121 "Unlaminated Plastics Profile Shape Manufacturing"
                , NAIC 326122 "Plastics Pipe and Pipe Fitting Manufacturing"
                , NAIC 326130 "Laminated Plastics Plate, Sheet (except Packaging), and Shape Manufacturing"
                , NAIC 326140 "Polystyrene Foam Product Manufacturing"
                , NAIC 326150 "Urethane and Other Foam Product (except Polystyrene) Manufacturing"
                , NAIC 326160 "Plastics Bottle Manufacturing"
                , NAIC 326191 "Plastics Plumbing Fixture Manufacturing"
                , NAIC 326199 "All Other Plastics Product Manufacturing"
                , NAIC 326211 "Tire Manufacturing (except Retreading)"
                , NAIC 326212 "Tire Retreading"
                , NAIC 326220 "Rubber and Plastics Hoses and Belting Manufacturing"
                , NAIC 326291 "Rubber Product Manufacturing for Mechanical Use"
                , NAIC 326299 "All Other Rubber Product Manufacturing"
                , NAIC 327110 "Pottery, Ceramics, and Plumbing Fixture Manufacturing"
                , NAIC 327120 "Clay Building Material and Refractories Manufacturing"
                , NAIC 327211 "Flat Glass Manufacturing"
                , NAIC 327212 "Other Pressed and Blown Glass and Glassware Manufacturing"
                , NAIC 327213 "Glass Container Manufacturing"
                , NAIC 327215 "Glass Product Manufacturing Made of Purchased Glass"
                , NAIC 327310 "Cement Manufacturing"
                , NAIC 327320 "Ready-Mix Concrete Manufacturing"
                , NAIC 327331 "Concrete Block and Brick Manufacturing"
                , NAIC 327332 "Concrete Pipe Manufacturing"
                , NAIC 327390 "Other Concrete Product Manufacturing"
                , NAIC 327410 "Lime Manufacturing"
                , NAIC 327420 "Gypsum Product Manufacturing"
                , NAIC 327910 "Abrasive Product Manufacturing"
                , NAIC 327991 "Cut Stone and Stone Product Manufacturing"
                , NAIC 327992 "Ground or Treated Mineral and Earth Manufacturing"
                , NAIC 327993 "Mineral Wool Manufacturing"
                , NAIC 327999 "All Other Miscellaneous Nonmetallic Mineral Product Manufacturing"
                , NAIC 331110 "Iron and Steel Mills and Ferroalloy Manufacturing"
                , NAIC 331210 "Iron and Steel Pipe and Tube Manufacturing from Purchased Steel"
                , NAIC 331221 "Rolled Steel Shape Manufacturing"
                , NAIC 331222 "Steel Wire Drawing"
                , NAIC 331313 "Alumina Refining and Primary Aluminum Production"
                , NAIC 331314 "Secondary Smelting and Alloying of Aluminum"
                , NAIC 331315 "Aluminum Sheet, Plate, and Foil Manufacturing"
                , NAIC 331318 "Other Aluminum Rolling, Drawing, and Extruding"
                , NAIC 331410 "Nonferrous Metal (except Aluminum) Smelting and Refining"
                , NAIC 331420 "Copper Rolling, Drawing, Extruding, and Alloying"
                , NAIC 331491 "Nonferrous Metal (except Copper and Aluminum) Rolling, Drawing, and Extruding"
                , NAIC 331492 "Secondary Smelting, Refining, and Alloying of Nonferrous Metal (except Copper and Aluminum)"
                , NAIC 331511 "Iron Foundries"
                , NAIC 331512 "Steel Investment Foundries"
                , NAIC 331513 "Steel Foundries (except Investment)"
                , NAIC 331523 "Nonferrous Metal Die-Casting Foundries"
                , NAIC 331524 "Aluminum Foundries (except Die-Casting)"
                , NAIC 331529 "Other Nonferrous Metal Foundries (except Die-Casting)"
                , NAIC 332111 "Iron and Steel Forging"
                , NAIC 332112 "Nonferrous Forging"
                , NAIC 332114 "Custom Roll Forming"
                , NAIC 332117 "Powder Metallurgy Part Manufacturing"
                , NAIC 332119 "Metal Crown, Closure, and Other Metal Stamping (except Automotive)"
                , NAIC 332215 "Metal Kitchen Cookware, Utensil, Cutlery, and Flatware (except Precious) Manufacturing"
                , NAIC 332216 "Saw Blade and Handtool Manufacturing"
                , NAIC 332311 "Prefabricated Metal Building and Component Manufacturing"
                , NAIC 332312 "Fabricated Structural Metal Manufacturing"
                , NAIC 332313 "Plate Work Manufacturing"
                , NAIC 332321 "Metal Window and Door Manufacturing"
                , NAIC 332322 "Sheet Metal Work Manufacturing"
                , NAIC 332323 "Ornamental and Architectural Metal Work Manufacturing"
                , NAIC 332410 "Power Boiler and Heat Exchanger Manufacturing"
                , NAIC 332420 "Metal Tank (Heavy Gauge) Manufacturing"
                , NAIC 332431 "Metal Can Manufacturing"
                , NAIC 332439 "Other Metal Container Manufacturing"
                , NAIC 332510 "Hardware Manufacturing"
                , NAIC 332613 "Spring Manufacturing"
                , NAIC 332618 "Other Fabricated Wire Product Manufacturing"
                , NAIC 332710 "Machine Shops"
                , NAIC 332721 "Precision Turned Product Manufacturing"
                , NAIC 332722 "Bolt, Nut, Screw, Rivet, and Washer Manufacturing"
                , NAIC 332811 "Metal Heat Treating"
                , NAIC 332812 "Metal Coating, Engraving (except Jewelry and Silverware), and Allied Services to Manufacturers"
                , NAIC 332813 "Electroplating, Plating, Polishing, Anodizing, and Coloring"
                , NAIC 332911 "Industrial Valve Manufacturing"
                , NAIC 332912 "Fluid Power Valve and Hose Fitting Manufacturing"
                , NAIC 332913 "Plumbing Fixture Fitting and Trim Manufacturing"
                , NAIC 332919 "Other Metal Valve and Pipe Fitting Manufacturing"
                , NAIC 332991 "Ball and Roller Bearing Manufacturing"
                , NAIC 332992 "Small Arms Ammunition Manufacturing"
                , NAIC 332993 "Ammunition (except Small Arms) Manufacturing"
                , NAIC 332994 "Small Arms, Ordnance, and Ordnance Accessories Manufacturing"
                , NAIC 332996 "Fabricated Pipe and Pipe Fitting Manufacturing"
                , NAIC 332999 "All Other Miscellaneous Fabricated Metal Product Manufacturing"
                , NAIC 333111 "Farm Machinery and Equipment Manufacturing"
                , NAIC 333112 "Lawn and Garden Tractor and Home Lawn and Garden Equipment Manufacturing"
                , NAIC 333120 "Construction Machinery Manufacturing"
                , NAIC 333131 "Mining Machinery and Equipment Manufacturing"
                , NAIC 333132 "Oil and Gas Field Machinery and Equipment Manufacturing"
                , NAIC 333241 "Food Product Machinery Manufacturing"
                , NAIC 333242 "Semiconductor Machinery Manufacturing"
                , NAIC 333243 "Sawmill, Woodworking, and Paper Machinery Manufacturing"
                , NAIC 333244 "Printing Machinery and Equipment Manufacturing"
                , NAIC 333249 "Other Industrial Machinery Manufacturing"
                , NAIC 333314 "Optical Instrument and Lens Manufacturing"
                , NAIC 333316 "Photographic and Photocopying Equipment Manufacturing"
                , NAIC 333318 "Other Commercial and Service Industry Machinery Manufacturing"
                , NAIC 333413 "Industrial and Commercial Fan and Blower and Air Purification Equipment Manufacturing"
                , NAIC 333414 "Heating Equipment (except Warm Air Furnaces) Manufacturing"
                , NAIC 333415 "Air-Conditioning and Warm Air Heating Equipment and Commercial and Industrial Refrigeration Equipment Manufacturing"
                , NAIC 333511 "Industrial Mold Manufacturing"
                , NAIC 333514 "Special Die and Tool, Die Set, Jig, and Fixture Manufacturing"
                , NAIC 333515 "Cutting Tool and Machine Tool Accessory Manufacturing"
                , NAIC 333517 "Machine Tool Manufacturing"
                , NAIC 333519 "Rolling Mill and Other Metalworking Machinery Manufacturing"
                , NAIC 333611 "Turbine and Turbine Generator Set Units Manufacturing"
                , NAIC 333612 "Speed Changer, Industrial High-Speed Drive, and Gear Manufacturing"
                , NAIC 333613 "Mechanical Power Transmission Equipment Manufacturing"
                , NAIC 333618 "Other Engine Equipment Manufacturing"
                , NAIC 333911 "Pump and Pumping Equipment Manufacturing"
                , NAIC 333912 "Air and Gas Compressor Manufacturing"
                , NAIC 333913 "Measuring and Dispensing Pump Manufacturing"
                , NAIC 333921 "Elevator and Moving Stairway Manufacturing"
                , NAIC 333922 "Conveyor and Conveying Equipment Manufacturing"
                , NAIC 333923 "Overhead Traveling Crane, Hoist, and Monorail System Manufacturing"
                , NAIC 333924 "Industrial Truck, Tractor, Trailer, and Stacker Machinery Manufacturing"
                , NAIC 333991 "Power-Driven Handtool Manufacturing"
                , NAIC 333992 "Welding and Soldering Equipment Manufacturing"
                , NAIC 333993 "Packaging Machinery Manufacturing"
                , NAIC 333994 "Industrial Process Furnace and Oven Manufacturing"
                , NAIC 333995 "Fluid Power Cylinder and Actuator Manufacturing"
                , NAIC 333996 "Fluid Power Pump and Motor Manufacturing"
                , NAIC 333997 "Scale and Balance Manufacturing"
                , NAIC 333999 "All Other Miscellaneous General Purpose Machinery Manufacturing"
                , NAIC 334111 "Electronic Computer Manufacturing"
                , NAIC 334112 "Computer Storage Device Manufacturing"
                , NAIC 334118 "Computer Terminal and Other Computer Peripheral Equipment Manufacturing"
                , NAIC 334210 "Telephone Apparatus Manufacturing"
                , NAIC 334220 "Radio and Television Broadcasting and Wireless Communications Equipment Manufacturing"
                , NAIC 334290 "Other Communications Equipment Manufacturing"
                , NAIC 334310 "Audio and Video Equipment Manufacturing"
                , NAIC 334412 "Bare Printed Circuit Board Manufacturing"
                , NAIC 334413 "Semiconductor and Related Device Manufacturing"
                , NAIC 334416 "Capacitor, Resistor, Coil, Transformer, and Other Inductor Manufacturing"
                , NAIC 334417 "Electronic Connector Manufacturing"
                , NAIC 334418 "Printed Circuit Assembly (Electronic Assembly) Manufacturing"
                , NAIC 334419 "Other Electronic Component Manufacturing"
                , NAIC 334510 "Electromedical and Electrotherapeutic Apparatus Manufacturing"
                , NAIC 334511 "Search, Detection, Navigation, Guidance, Aeronautical, and Nautical System and Instrument Manufacturing"
                , NAIC 334512 "Automatic Environmental Control Manufacturing for Residential, Commercial, and Appliance Use"
                , NAIC 334513 "Instruments and Related Products Manufacturing for Measuring, Displaying, and Controlling Industrial Process Variables"
                , NAIC 334514 "Totalizing Fluid Meter and Counting Device Manufacturing"
                , NAIC 334515 "Instrument Manufacturing for Measuring and Testing Electricity and Electrical Signals"
                , NAIC 334516 "Analytical Laboratory Instrument Manufacturing"
                , NAIC 334517 "Irradiation Apparatus Manufacturing"
                , NAIC 334519 "Other Measuring and Controlling Device Manufacturing"
                , NAIC 334613 "Blank Magnetic and Optical Recording Media Manufacturing"
                , NAIC 334614 "Software and Other Prerecorded Compact Disc, Tape, and Record Reproducing"
                , NAIC 335110 "Electric Lamp Bulb and Part Manufacturing"
                , NAIC 335121 "Residential Electric Lighting Fixture Manufacturing"
                , NAIC 335122 "Commercial, Industrial, and Institutional Electric Lighting Fixture Manufacturing"
                , NAIC 335129 "Other Lighting Equipment Manufacturing"
                , NAIC 335210 "Small Electrical Appliance Manufacturing"
                , NAIC 335221 "Household Cooking Appliance Manufacturing"
                , NAIC 335222 "Household Refrigerator and Home Freezer Manufacturing"
                , NAIC 335224 "Household Laundry Equipment Manufacturing"
                , NAIC 335228 "Other Major Household Appliance Manufacturing"
                , NAIC 335311 "Power, Distribution, and Specialty Transformer Manufacturing"
                , NAIC 335312 "Motor and Generator Manufacturing"
                , NAIC 335313 "Switchgear and Switchboard Apparatus Manufacturing"
                , NAIC 335314 "Relay and Industrial Control Manufacturing"
                , NAIC 335911 "Storage Battery Manufacturing"
                , NAIC 335912 "Primary Battery Manufacturing"
                , NAIC 335921 "Fiber Optic Cable Manufacturing"
                , NAIC 335929 "Other Communication and Energy Wire Manufacturing"
                , NAIC 335931 "Current-Carrying Wiring Device Manufacturing"
                , NAIC 335932 "Noncurrent-Carrying Wiring Device Manufacturing"
                , NAIC 335991 "Carbon and Graphite Product Manufacturing"
                , NAIC 335999 "All Other Miscellaneous Electrical Equipment and Component Manufacturing"
                , NAIC 336111 "Automobile Manufacturing"
                , NAIC 336112 "Light Truck and Utility Vehicle Manufacturing"
                , NAIC 336120 "Heavy Duty Truck Manufacturing"
                , NAIC 336211 "Motor Vehicle Body Manufacturing"
                , NAIC 336212 "Truck Trailer Manufacturing"
                , NAIC 336213 "Motor Home Manufacturing"
                , NAIC 336214 "Travel Trailer and Camper Manufacturing"
                , NAIC 336310 "Motor Vehicle Gasoline Engine and Engine Parts Manufacturing"
                , NAIC 336320 "Motor Vehicle Electrical and Electronic Equipment Manufacturing"
                , NAIC 336330 "Motor Vehicle Steering and Suspension Components (except Spring) Manufacturing"
                , NAIC 336340 "Motor Vehicle Brake System Manufacturing"
                , NAIC 336350 "Motor Vehicle Transmission and Power Train Parts Manufacturing"
                , NAIC 336360 "Motor Vehicle Seating and Interior Trim Manufacturing"
                , NAIC 336370 "Motor Vehicle Metal Stamping"
                , NAIC 336390 "Other Motor Vehicle Parts Manufacturing"
                , NAIC 336411 "Aircraft Manufacturing"
                , NAIC 336412 "Aircraft Engine and Engine Parts Manufacturing"
                , NAIC 336413 "Other Aircraft Parts and Auxiliary Equipment Manufacturing"
                , NAIC 336414 "Guided Missile and Space Vehicle Manufacturing"
                , NAIC 336415 "Guided Missile and Space Vehicle Propulsion Unit and Propulsion Unit Parts Manufacturing"
                , NAIC 336419 "Other Guided Missile and Space Vehicle Parts and Auxiliary Equipment Manufacturing"
                , NAIC 336510 "Railroad Rolling Stock Manufacturing"
                , NAIC 336611 "Ship Building and Repairing"
                , NAIC 336612 "Boat Building"
                , NAIC 336991 "Motorcycle, Bicycle, and Parts Manufacturing"
                , NAIC 336992 "Military Armored Vehicle, Tank, and Tank Component Manufacturing"
                , NAIC 336999 "All Other Transportation Equipment Manufacturing"
                , NAIC 337110 "Wood Kitchen Cabinet and Countertop Manufacturing"
                , NAIC 337121 "Upholstered Household Furniture Manufacturing"
                , NAIC 337122 "Nonupholstered Wood Household Furniture Manufacturing"
                , NAIC 337124 "Metal Household Furniture Manufacturing"
                , NAIC 337125 "Household Furniture (except Wood and Metal) Manufacturing"
                , NAIC 337127 "Institutional Furniture Manufacturing"
                , NAIC 337211 "Wood Office Furniture Manufacturing"
                , NAIC 337212 "Custom Architectural Woodwork and Millwork Manufacturing"
                , NAIC 337214 "Office Furniture (except Wood) Manufacturing"
                , NAIC 337215 "Showcase, Partition, Shelving, and Locker Manufacturing"
                , NAIC 337910 "Mattress Manufacturing"
                , NAIC 337920 "Blind and Shade Manufacturing"
                , NAIC 339112 "Surgical and Medical Instrument Manufacturing"
                , NAIC 339113 "Surgical Appliance and Supplies Manufacturing"
                , NAIC 339114 "Dental Equipment and Supplies Manufacturing"
                , NAIC 339115 "Ophthalmic Goods Manufacturing"
                , NAIC 339116 "Dental Laboratories"
                , NAIC 339910 "Jewelry and Silverware Manufacturing"
                , NAIC 339920 "Sporting and Athletic Goods Manufacturing"
                , NAIC 339930 "Doll, Toy, and Game Manufacturing"
                , NAIC 339940 "Office Supplies (except Paper) Manufacturing"
                , NAIC 339950 "Sign Manufacturing"
                , NAIC 339991 "Gasket, Packing, and Sealing Device Manufacturing"
                , NAIC 339992 "Musical Instrument Manufacturing"
                , NAIC 339993 "Fastener, Button, Needle, and Pin Manufacturing"
                , NAIC 339994 "Broom, Brush, and Mop Manufacturing"
                , NAIC 339995 "Burial Casket Manufacturing"
                , NAIC 339999 "All Other Miscellaneous Manufacturing"
                , NAIC 423110 "Automobile and Other Motor Vehicle Merchant Wholesalers"
                , NAIC 423120 "Motor Vehicle Supplies and New Parts Merchant Wholesalers"
                , NAIC 423130 "Tire and Tube Merchant Wholesalers"
                , NAIC 423140 "Motor Vehicle Parts (Used) Merchant Wholesalers"
                , NAIC 423210 "Furniture Merchant Wholesalers"
                , NAIC 423220 "Home Furnishing Merchant Wholesalers"
                , NAIC 423310 "Lumber, Plywood, Millwork, and Wood Panel Merchant Wholesalers"
                , NAIC 423320 "Brick, Stone, and Related Construction Material Merchant Wholesalers"
                , NAIC 423330 "Roofing, Siding, and Insulation Material Merchant Wholesalers"
                , NAIC 423390 "Other Construction Material Merchant Wholesalers"
                , NAIC 423410 "Photographic Equipment and Supplies Merchant Wholesalers"
                , NAIC 423420 "Office Equipment Merchant Wholesalers"
                , NAIC 423430 "Computer and Computer Peripheral Equipment and Software Merchant Wholesalers"
                , NAIC 423440 "Other Commercial Equipment Merchant Wholesalers"
                , NAIC 423450 "Medical, Dental, and Hospital Equipment and Supplies Merchant Wholesalers"
                , NAIC 423460 "Ophthalmic Goods Merchant Wholesalers"
                , NAIC 423490 "Other Professional Equipment and Supplies Merchant Wholesalers"
                , NAIC 423510 "Metal Service Centers and Other Metal Merchant Wholesalers"
                , NAIC 423520 "Coal and Other Mineral and Ore Merchant Wholesalers"
                , NAIC 423610 "Electrical Apparatus and Equipment, Wiring Supplies, and Related Equipment Merchant Wholesalers"
                , NAIC 423620 "Household Appliances, Electric Housewares, and Consumer Electronics Merchant Wholesalers"
                , NAIC 423690 "Other Electronic Parts and Equipment Merchant Wholesalers"
                , NAIC 423710 "Hardware Merchant Wholesalers"
                , NAIC 423720 "Plumbing and Heating Equipment and Supplies (Hydronics) Merchant Wholesalers"
                , NAIC 423730 "Warm Air Heating and Air-Conditioning Equipment and Supplies Merchant Wholesalers"
                , NAIC 423740 "Refrigeration Equipment and Supplies Merchant Wholesalers"
                , NAIC 423810 "Construction and Mining (except Oil Well) Machinery and Equipment Merchant Wholesalers"
                , NAIC 423820 "Farm and Garden Machinery and Equipment Merchant Wholesalers"
                , NAIC 423830 "Industrial Machinery and Equipment Merchant Wholesalers"
                , NAIC 423840 "Industrial Supplies Merchant Wholesalers"
                , NAIC 423850 "Service Establishment Equipment and Supplies Merchant Wholesalers"
                , NAIC 423860 "Transportation Equipment and Supplies (except Motor Vehicle) Merchant Wholesalers"
                , NAIC 423910 "Sporting and Recreational Goods and Supplies Merchant Wholesalers"
                , NAIC 423920 "Toy and Hobby Goods and Supplies Merchant Wholesalers"
                , NAIC 423930 "Recyclable Material Merchant Wholesalers"
                , NAIC 423940 "Jewelry, Watch, Precious Stone, and Precious Metal Merchant Wholesalers"
                , NAIC 423990 "Other Miscellaneous Durable Goods Merchant Wholesalers"
                , NAIC 424110 "Printing and Writing Paper Merchant Wholesalers"
                , NAIC 424120 "Stationery and Office Supplies Merchant Wholesalers"
                , NAIC 424130 "Industrial and Personal Service Paper Merchant Wholesalers"
                , NAIC 424210 "Drugs and Druggists’ Sundries Merchant Wholesalers"
                , NAIC 424310 "Piece Goods, Notions, and Other Dry Goods Merchant Wholesalers"
                , NAIC 424320 "Men’s and Boys’ Clothing and Furnishings Merchant Wholesalers"
                , NAIC 424330 "Women’s, Children’s, and Infants’ Clothing and Accessories Merchant Wholesalers"
                , NAIC 424340 "Footwear Merchant Wholesalers"
                , NAIC 424410 "General Line Grocery Merchant Wholesalers"
                , NAIC 424420 "Packaged Frozen Food Merchant Wholesalers"
                , NAIC 424430 "Dairy Product (except Dried or Canned) Merchant Wholesalers"
                , NAIC 424440 "Poultry and Poultry Product Merchant Wholesalers"
                , NAIC 424450 "Confectionery Merchant Wholesalers"
                , NAIC 424460 "Fish and Seafood Merchant Wholesalers"
                , NAIC 424470 "Meat and Meat Product Merchant Wholesalers"
                , NAIC 424480 "Fresh Fruit and Vegetable Merchant Wholesalers"
                , NAIC 424490 "Other Grocery and Related Products Merchant Wholesalers"
                , NAIC 424510 "Grain and Field Bean Merchant Wholesalers"
                , NAIC 424520 "Livestock Merchant Wholesalers"
                , NAIC 424590 "Other Farm Product Raw Material Merchant Wholesalers"
                , NAIC 424610 "Plastics Materials and Basic Forms and Shapes Merchant Wholesalers"
                , NAIC 424690 "Other Chemical and Allied Products Merchant Wholesalers"
                , NAIC 424710 "Petroleum Bulk Stations and Terminals"
                , NAIC 424720 "Petroleum and Petroleum Products Merchant Wholesalers (except Bulk Stations and Terminals)"
                , NAIC 424810 "Beer and Ale Merchant Wholesalers"
                , NAIC 424820 "Wine and Distilled Alcoholic Beverage Merchant Wholesalers"
                , NAIC 424910 "Farm Supplies Merchant Wholesalers"
                , NAIC 424920 "Book, Periodical, and Newspaper Merchant Wholesalers"
                , NAIC 424930 "Flower, Nursery Stock, and Florists’ Supplies Merchant Wholesalers"
                , NAIC 424940 "Tobacco and Tobacco Product Merchant Wholesalers"
                , NAIC 424950 "Paint, Varnish, and Supplies Merchant Wholesalers"
                , NAIC 424990 "Other Miscellaneous Nondurable Goods Merchant Wholesalers"
                , NAIC 425110 "Business to Business Electronic Markets"
                , NAIC 425120 "Wholesale Trade Agents and Brokers"
                , NAIC 441110 "New Car Dealers"
                , NAIC 441120 "Used Car Dealers"
                , NAIC 441210 "Recreational Vehicle Dealers"
                , NAIC 441222 "Boat Dealers"
                , NAIC 441228 "Motorcycle, ATV, and All Other Motor Vehicle Dealers"
                , NAIC 441310 "Automotive Parts and Accessories Stores"
                , NAIC 441320 "Tire Dealers"
                , NAIC 442110 "Furniture Stores"
                , NAIC 442210 "Floor Covering Stores"
                , NAIC 442291 "Window Treatment Stores"
                , NAIC 442299 "All Other Home Furnishings Stores"
                , NAIC 443141 "Household Appliance Stores"
                , NAIC 443142 "Electronics Stores"
                , NAIC 444110 "Home Centers"
                , NAIC 444120 "Paint and Wallpaper Stores"
                , NAIC 444130 "Hardware Stores"
                , NAIC 444190 "Other Building Material Dealers"
                , NAIC 444210 "Outdoor Power Equipment Stores"
                , NAIC 444220 "Nursery, Garden Center, and Farm Supply Stores"
                , NAIC 445110 "Supermarkets and Other Grocery (except Convenience) Stores"
                , NAIC 445120 "Convenience Stores"
                , NAIC 445210 "Meat Markets"
                , NAIC 445220 "Fish and Seafood Markets"
                , NAIC 445230 "Fruit and Vegetable Markets"
                , NAIC 445291 "Baked Goods Stores"
                , NAIC 445292 "Confectionery and Nut Stores"
                , NAIC 445299 "All Other Specialty Food Stores"
                , NAIC 445310 "Beer, Wine, and Liquor Stores"
                , NAIC 446110 "Pharmacies and Drug Stores"
                , NAIC 446120 "Cosmetics, Beauty Supplies, and Perfume Stores"
                , NAIC 446130 "Optical Goods Stores"
                , NAIC 446191 "Food (Health) Supplement Stores"
                , NAIC 446199 "All Other Health and Personal Care Stores"
                , NAIC 447110 "Gasoline Stations with Convenience Stores"
                , NAIC 447190 "Other Gasoline Stations"
                , NAIC 448110 "Men’s Clothing Stores"
                , NAIC 448120 "Women’s Clothing Stores"
                , NAIC 448130 "Children’s and Infants’ Clothing Stores"
                , NAIC 448140 "Family Clothing Stores"
                , NAIC 448150 "Clothing Accessories Stores"
                , NAIC 448190 "Other Clothing Stores"
                , NAIC 448210 "Shoe Stores"
                , NAIC 448310 "Jewelry Stores"
                , NAIC 448320 "Luggage and Leather Goods Stores"
                , NAIC 451110 "Sporting Goods Stores"
                , NAIC 451120 "Hobby, Toy, and Game Stores"
                , NAIC 451130 "Sewing, Needlework, and Piece Goods Stores"
                , NAIC 451140 "Musical Instrument and Supplies Stores"
                , NAIC 451211 "Book Stores"
                , NAIC 451212 "News Dealers and Newsstands"
                , NAIC 452111 "Department Stores (except Discount Department Stores)"
                , NAIC 452112 "Discount Department Stores"
                , NAIC 452910 "Warehouse Clubs and Supercenters"
                , NAIC 452990 "All Other General Merchandise Stores"
                , NAIC 453110 "Florists"
                , NAIC 453210 "Office Supplies and Stationery Stores"
                , NAIC 453220 "Gift, Novelty, and Souvenir Stores"
                , NAIC 453310 "Used Merchandise Stores"
                , NAIC 453910 "Pet and Pet Supplies Stores"
                , NAIC 453920 "Art Dealers"
                , NAIC 453930 "Manufactured (Mobile) Home Dealers"
                , NAIC 453991 "Tobacco Stores"
                , NAIC 453998 "All Other Miscellaneous Store Retailers (except Tobacco Stores)"
                , NAIC 454111 "Electronic Shopping"
                , NAIC 454112 "Electronic Auctions"
                , NAIC 454113 "Mail-Order Houses"
                , NAIC 454210 "Vending Machine Operators"
                , NAIC 454310 "Fuel Dealers"
                , NAIC 454390 "Other Direct Selling Establishments"
                , NAIC 481111 "Scheduled Passenger Air Transportation"
                , NAIC 481112 "Scheduled Freight Air Transportation"
                , NAIC 481211 "Nonscheduled Chartered Passenger Air Transportation"
                , NAIC 481212 "Nonscheduled Chartered Freight Air Transportation"
                , NAIC 481219 "Other Nonscheduled Air Transportation"
                , NAIC 482111 "Line-Haul Railroads"
                , NAIC 482112 "Short Line Railroads"
                , NAIC 483111 "Deep Sea Freight Transportation"
                , NAIC 483112 "Deep Sea Passenger Transportation"
                , NAIC 483113 "Coastal and Great Lakes Freight Transportation"
                , NAIC 483114 "Coastal and Great Lakes Passenger Transportation"
                , NAIC 483211 "Inland Water Freight Transportation"
                , NAIC 483212 "Inland Water Passenger Transportation"
                , NAIC 484110 "General Freight Trucking, Local"
                , NAIC 484121 "General Freight Trucking, Long-Distance, Truckload"
                , NAIC 484122 "General Freight Trucking, Long-Distance, Less Than Truckload"
                , NAIC 484210 "Used Household and Office Goods Moving"
                , NAIC 484220 "Specialized Freight (except Used Goods) Trucking, Local"
                , NAIC 484230 "Specialized Freight (except Used Goods) Trucking, Long-Distance"
                , NAIC 485111 "Mixed Mode Transit Systems"
                , NAIC 485112 "Commuter Rail Systems"
                , NAIC 485113 "Bus and Other Motor Vehicle Transit Systems"
                , NAIC 485119 "Other Urban Transit Systems"
                , NAIC 485210 "Interurban and Rural Bus Transportation"
                , NAIC 485310 "Taxi Service"
                , NAIC 485320 "Limousine Service"
                , NAIC 485410 "School and Employee Bus Transportation"
                , NAIC 485510 "Charter Bus Industry"
                , NAIC 485991 "Special Needs Transportation"
                , NAIC 485999 "All Other Transit and Ground Passenger Transportation"
                , NAIC 486110 "Pipeline Transportation of Crude Oil"
                , NAIC 486210 "Pipeline Transportation of Natural Gas"
                , NAIC 486910 "Pipeline Transportation of Refined Petroleum Products"
                , NAIC 486990 "All Other Pipeline Transportation"
                , NAIC 487110 "Scenic and Sightseeing Transportation, Land"
                , NAIC 487210 "Scenic and Sightseeing Transportation, Water"
                , NAIC 487990 "Scenic and Sightseeing Transportation, Other"
                , NAIC 488111 "Air Traffic Control"
                , NAIC 488119 "Other Airport Operations"
                , NAIC 488190 "Other Support Activities for Air Transportation"
                , NAIC 488210 "Support Activities for Rail Transportation"
                , NAIC 488310 "Port and Harbor Operations"
                , NAIC 488320 "Marine Cargo Handling"
                , NAIC 488330 "Navigational Services to Shipping"
                , NAIC 488390 "Other Support Activities for Water Transportation"
                , NAIC 488410 "Motor Vehicle Towing"
                , NAIC 488490 "Other Support Activities for Road Transportation"
                , NAIC 488510 "Freight Transportation Arrangement"
                , NAIC 488991 "Packing and Crating"
                , NAIC 488999 "All Other Support Activities for Transportation"
                , NAIC 491110 "Postal Service"
                , NAIC 492110 "Couriers and Express Delivery Services"
                , NAIC 492210 "Local Messengers and Local Delivery"
                , NAIC 493110 "General Warehousing and Storage"
                , NAIC 493120 "Refrigerated Warehousing and Storage"
                , NAIC 493130 "Farm Product Warehousing and Storage"
                , NAIC 493190 "Other Warehousing and Storage"
                , NAIC 511110 "Newspaper Publishers"
                , NAIC 511120 "Periodical Publishers"
                , NAIC 511130 "Book Publishers"
                , NAIC 511140 "Directory and Mailing List Publishers"
                , NAIC 511191 "Greeting Card Publishers"
                , NAIC 511199 "All Other Publishers"
                , NAIC 511210 "Software Publishers"
                , NAIC 512110 "Motion Picture and Video Production"
                , NAIC 512120 "Motion Picture and Video Distribution"
                , NAIC 512131 "Motion Picture Theaters (except Drive-Ins)"
                , NAIC 512132 "Drive-In Motion Picture Theaters"
                , NAIC 512191 "Teleproduction and Other Postproduction Services"
                , NAIC 512199 "Other Motion Picture and Video Industries"
                , NAIC 512210 "Record Production"
                , NAIC 512220 "Integrated Record Production/Distribution"
                , NAIC 512230 "Music Publishers"
                , NAIC 512240 "Sound Recording Studios"
                , NAIC 512290 "Other Sound Recording Industries"
                , NAIC 515111 "Radio Networks"
                , NAIC 515112 "Radio Stations"
                , NAIC 515120 "Television Broadcasting"
                , NAIC 515210 "Cable and Other Subscription Programming"
                , NAIC 517110 "Wired Telecommunications Carriers"
                , NAIC 517210 "Wireless Telecommunications Carriers (except Satellite)"
                , NAIC 517410 "Satellite Telecommunications"
                , NAIC 517911 "Telecommunications Resellers"
                , NAIC 517919 "All Other Telecommunications"
                , NAIC 518210 "Data Processing, Hosting, and Related Services"
                , NAIC 519110 "News Syndicates"
                , NAIC 519120 "Libraries and Archives"
                , NAIC 519130 "Internet Publishing and Broadcasting and Web Search Portals"
                , NAIC 519190 "All Other Information Services"
                , NAIC 521110 "Monetary Authorities-Central Bank"
                , NAIC 522110 "Commercial Banking"
                , NAIC 522120 "Savings Institutions"
                , NAIC 522130 "Credit Unions"
                , NAIC 522190 "Other Depository Credit Intermediation"
                , NAIC 522210 "Credit Card Issuing"
                , NAIC 522220 "Sales Financing"
                , NAIC 522291 "Consumer Lending"
                , NAIC 522292 "Real Estate Credit"
                , NAIC 522293 "International Trade Financing"
                , NAIC 522294 "Secondary Market Financing"
                , NAIC 522298 "All Other Nondepository Credit Intermediation"
                , NAIC 522310 "Mortgage and Nonmortgage Loan Brokers"
                , NAIC 522320 "Financial Transactions Processing, Reserve, and Clearinghouse Activities"
                , NAIC 522390 "Other Activities Related to Credit Intermediation"
                , NAIC 523110 "Investment Banking and Securities Dealing"
                , NAIC 523120 "Securities Brokerage"
                , NAIC 523130 "Commodity Contracts Dealing"
                , NAIC 523140 "Commodity Contracts Brokerage"
                , NAIC 523210 "Securities and Commodity Exchanges"
                , NAIC 523910 "Miscellaneous Intermediation"
                , NAIC 523920 "Portfolio Management"
                , NAIC 523930 "Investment Advice"
                , NAIC 523991 "Trust, Fiduciary, and Custody Activities"
                , NAIC 523999 "Miscellaneous Financial Investment Activities"
                , NAIC 524113 "Direct Life Insurance Carriers"
                , NAIC 524114 "Direct Health and Medical Insurance Carriers"
                , NAIC 524126 "Direct Property and Casualty Insurance Carriers"
                , NAIC 524127 "Direct Title Insurance Carriers"
                , NAIC 524128 "Other Direct Insurance (except Life, Health, and Medical) Carriers"
                , NAIC 524130 "Reinsurance Carriers"
                , NAIC 524210 "Insurance Agencies and Brokerages"
                , NAIC 524291 "Claims Adjusting"
                , NAIC 524292 "Third Party Administration of Insurance and Pension Funds"
                , NAIC 524298 "All Other Insurance Related Activities"
                , NAIC 525110 "Pension Funds"
                , NAIC 525120 "Health and Welfare Funds"
                , NAIC 525190 "Other Insurance Funds"
                , NAIC 525910 "Open-End Investment Funds"
                , NAIC 525920 "Trusts, Estates, and Agency Accounts"
                , NAIC 525990 "Other Financial Vehicles"
                , NAIC 531110 "Lessors of Residential Buildings and Dwellings"
                , NAIC 531120 "Lessors of Nonresidential Buildings (except Miniwarehouses)"
                , NAIC 531130 "Lessors of Miniwarehouses and Self-Storage Units"
                , NAIC 531190 "Lessors of Other Real Estate Property"
                , NAIC 531210 "Offices of Real Estate Agents and Brokers"
                , NAIC 531311 "Residential Property Managers"
                , NAIC 531312 "Nonresidential Property Managers"
                , NAIC 531320 "Offices of Real Estate Appraisers"
                , NAIC 531390 "Other Activities Related to Real Estate"
                , NAIC 532111 "Passenger Car Rental"
                , NAIC 532112 "Passenger Car Leasing"
                , NAIC 532120 "Truck, Utility Trailer, and RV (Recreational Vehicle) Rental and Leasing"
                , NAIC 532210 "Consumer Electronics and Appliances Rental"
                , NAIC 532220 "Formal Wear and Costume Rental"
                , NAIC 532230 "Video Tape and Disc Rental"
                , NAIC 532291 "Home Health Equipment Rental"
                , NAIC 532292 "Recreational Goods Rental"
                , NAIC 532299 "All Other Consumer Goods Rental"
                , NAIC 532310 "General Rental Centers"
                , NAIC 532411 "Commercial Air, Rail, and Water Transportation Equipment Rental and Leasing"
                , NAIC 532412 "Construction, Mining, and Forestry Machinery and Equipment Rental and Leasing"
                , NAIC 532420 "Office Machinery and Equipment Rental and Leasing"
                , NAIC 532490 "Other Commercial and Industrial Machinery and Equipment Rental and Leasing"
                , NAIC 533110 "Lessors of Nonfinancial Intangible Assets (except Copyrighted Works)"
                , NAIC 541110 "Offices of Lawyers"
                , NAIC 541120 "Offices of Notaries"
                , NAIC 541191 "Title Abstract and Settlement Offices"
                , NAIC 541199 "All Other Legal Services"
                , NAIC 541211 "Offices of Certified Public Accountants"
                , NAIC 541213 "Tax Preparation Services"
                , NAIC 541214 "Payroll Services"
                , NAIC 541219 "Other Accounting Services"
                , NAIC 541310 "Architectural Services"
                , NAIC 541320 "Landscape Architectural Services"
                , NAIC 541330 "Engineering Services"
                , NAIC 541340 "Drafting Services"
                , NAIC 541350 "Building Inspection Services"
                , NAIC 541360 "Geophysical Surveying and Mapping Services"
                , NAIC 541370 "Surveying and Mapping (except Geophysical) Services"
                , NAIC 541380 "Testing Laboratories"
                , NAIC 541410 "Interior Design Services"
                , NAIC 541420 "Industrial Design Services"
                , NAIC 541430 "Graphic Design Services"
                , NAIC 541490 "Other Specialized Design Services"
                , NAIC 541511 "Custom Computer Programming Services"
                , NAIC 541512 "Computer Systems Design Services"
                , NAIC 541513 "Computer Facilities Management Services"
                , NAIC 541519 "Other Computer Related Services"
                , NAIC 541611 "Administrative Management and General Management Consulting Services"
                , NAIC 541612 "Human Resources Consulting Services"
                , NAIC 541613 "Marketing Consulting Services"
                , NAIC 541614 "Process, Physical Distribution, and Logistics Consulting Services"
                , NAIC 541618 "Other Management Consulting Services"
                , NAIC 541620 "Environmental Consulting Services"
                , NAIC 541690 "Other Scientific and Technical Consulting Services"
                , NAIC 541711 "Research and Development in Biotechnology"
                , NAIC 541712 "Research and Development in the Physical, Engineering, and Life Sciences (except Biotechnology)"
                , NAIC 541720 "Research and Development in the Social Sciences and Humanities"
                , NAIC 541810 "Advertising Agencies"
                , NAIC 541820 "Public Relations Agencies"
                , NAIC 541830 "Media Buying Agencies"
                , NAIC 541840 "Media Representatives"
                , NAIC 541850 "Outdoor Advertising"
                , NAIC 541860 "Direct Mail Advertising"
                , NAIC 541870 "Advertising Material Distribution Services"
                , NAIC 541890 "Other Services Related to Advertising"
                , NAIC 541910 "Marketing Research and Public Opinion Polling"
                , NAIC 541921 "Photography Studios, Portrait"
                , NAIC 541922 "Commercial Photography"
                , NAIC 541930 "Translation and Interpretation Services"
                , NAIC 541940 "Veterinary Services"
                , NAIC 541990 "All Other Professional, Scientific, and Technical Services"
                , NAIC 551111 "Offices of Bank Holding Companies"
                , NAIC 551112 "Offices of Other Holding Companies"
                , NAIC 551114 "Corporate, Subsidiary, and Regional Managing Offices"
                , NAIC 561110 "Office Administrative Services"
                , NAIC 561210 "Facilities Support Services"
                , NAIC 561311 "Employment Placement Agencies"
                , NAIC 561312 "Executive Search Services"
                , NAIC 561320 "Temporary Help Services"
                , NAIC 561330 "Professional Employer Organizations"
                , NAIC 561410 "Document Preparation Services"
                , NAIC 561421 "Telephone Answering Services"
                , NAIC 561422 "Telemarketing Bureaus and Other Contact Centers"
                , NAIC 561431 "Private Mail Centers"
                , NAIC 561439 "Other Business Service Centers (including Copy Shops)"
                , NAIC 561440 "Collection Agencies"
                , NAIC 561450 "Credit Bureaus"
                , NAIC 561491 "Repossession Services"
                , NAIC 561492 "Court Reporting and Stenotype Services"
                , NAIC 561499 "All Other Business Support Services"
                , NAIC 561510 "Travel Agencies"
                , NAIC 561520 "Tour Operators"
                , NAIC 561591 "Convention and Visitors Bureaus"
                , NAIC 561599 "All Other Travel Arrangement and Reservation Services"
                , NAIC 561611 "Investigation Services"
                , NAIC 561612 "Security Guards and Patrol Services"
                , NAIC 561613 "Armored Car Services"
                , NAIC 561621 "Security Systems Services (except Locksmiths)"
                , NAIC 561622 "Locksmiths"
                , NAIC 561710 "Exterminating and Pest Control Services"
                , NAIC 561720 "Janitorial Services"
                , NAIC 561730 "Landscaping Services"
                , NAIC 561740 "Carpet and Upholstery Cleaning Services"
                , NAIC 561790 "Other Services to Buildings and Dwellings"
                , NAIC 561910 "Packaging and Labeling Services"
                , NAIC 561920 "Convention and Trade Show Organizers"
                , NAIC 561990 "All Other Support Services"
                , NAIC 562111 "Solid Waste Collection"
                , NAIC 562112 "Hazardous Waste Collection"
                , NAIC 562119 "Other Waste Collection"
                , NAIC 562211 "Hazardous Waste Treatment and Disposal"
                , NAIC 562212 "Solid Waste Landfill"
                , NAIC 562213 "Solid Waste Combustors and Incinerators"
                , NAIC 562219 "Other Nonhazardous Waste Treatment and Disposal"
                , NAIC 562910 "Remediation Services"
                , NAIC 562920 "Materials Recovery Facilities"
                , NAIC 562991 "Septic Tank and Related Services"
                , NAIC 562998 "All Other Miscellaneous Waste Management Services"
                , NAIC 611110 "Elementary and Secondary Schools"
                , NAIC 611210 "Junior Colleges"
                , NAIC 611310 "Colleges, Universities, and Professional Schools"
                , NAIC 611410 "Business and Secretarial Schools"
                , NAIC 611420 "Computer Training"
                , NAIC 611430 "Professional and Management Development Training"
                , NAIC 611511 "Cosmetology and Barber Schools"
                , NAIC 611512 "Flight Training"
                , NAIC 611513 "Apprenticeship Training"
                , NAIC 611519 "Other Technical and Trade Schools"
                , NAIC 611610 "Fine Arts Schools"
                , NAIC 611620 "Sports and Recreation Instruction"
                , NAIC 611630 "Language Schools"
                , NAIC 611691 "Exam Preparation and Tutoring"
                , NAIC 611692 "Automobile Driving Schools"
                , NAIC 611699 "All Other Miscellaneous Schools and Instruction"
                , NAIC 611710 "Educational Support Services"
                , NAIC 621111 "Offices of Physicians (except Mental Health Specialists)"
                , NAIC 621112 "Offices of Physicians, Mental Health Specialists"
                , NAIC 621210 "Offices of Dentists"
                , NAIC 621310 "Offices of Chiropractors"
                , NAIC 621320 "Offices of Optometrists"
                , NAIC 621330 "Offices of Mental Health Practitioners (except Physicians)"
                , NAIC 621340 "Offices of Physical, Occupational and Speech Therapists, and Audiologists"
                , NAIC 621391 "Offices of Podiatrists"
                , NAIC 621399 "Offices of All Other Miscellaneous Health Practitioners"
                , NAIC 621410 "Family Planning Centers"
                , NAIC 621420 "Outpatient Mental Health and Substance Abuse Centers"
                , NAIC 621491 "HMO Medical Centers"
                , NAIC 621492 "Kidney Dialysis Centers"
                , NAIC 621493 "Freestanding Ambulatory Surgical and Emergency Centers"
                , NAIC 621498 "All Other Outpatient Care Centers"
                , NAIC 621511 "Medical Laboratories"
                , NAIC 621512 "Diagnostic Imaging Centers"
                , NAIC 621610 "Home Health Care Services"
                , NAIC 621910 "Ambulance Services"
                , NAIC 621991 "Blood and Organ Banks"
                , NAIC 621999 "All Other Miscellaneous Ambulatory Health Care Services"
                , NAIC 622110 "General Medical and Surgical Hospitals"
                , NAIC 622210 "Psychiatric and Substance Abuse Hospitals"
                , NAIC 622310 "Specialty (except Psychiatric and Substance Abuse) Hospitals"
                , NAIC 623110 "Nursing Care Facilities (Skilled Nursing Facilities)"
                , NAIC 623210 "Residential Intellectual and Developmental Disability Facilities"
                , NAIC 623220 "Residential Mental Health and Substance Abuse Facilities"
                , NAIC 623311 "Continuing Care Retirement Communities"
                , NAIC 623312 "Assisted Living Facilities for the Elderly"
                , NAIC 623990 "Other Residential Care Facilities"
                , NAIC 624110 "Child and Youth Services"
                , NAIC 624120 "Services for the Elderly and Persons with Disabilities"
                , NAIC 624190 "Other Individual and Family Services"
                , NAIC 624210 "Community Food Services"
                , NAIC 624221 "Temporary Shelters"
                , NAIC 624229 "Other Community Housing Services"
                , NAIC 624230 "Emergency and Other Relief Services"
                , NAIC 624310 "Vocational Rehabilitation Services"
                , NAIC 624410 "Child Day Care Services"
                , NAIC 711110 "Theater Companies and Dinner Theaters"
                , NAIC 711120 "Dance Companies"
                , NAIC 711130 "Musical Groups and Artists"
                , NAIC 711190 "Other Performing Arts Companies"
                , NAIC 711211 "Sports Teams and Clubs"
                , NAIC 711212 "Racetracks"
                , NAIC 711219 "Other Spectator Sports"
                , NAIC 711310 "Promoters of Performing Arts, Sports, and Similar Events with Facilities"
                , NAIC 711320 "Promoters of Performing Arts, Sports, and Similar Events without Facilities"
                , NAIC 711410 "Agents and Managers for Artists, Athletes, Entertainers, and Other Public Figures"
                , NAIC 711510 "Independent Artists, Writers, and Performers"
                , NAIC 712110 "Museums"
                , NAIC 712120 "Historical Sites"
                , NAIC 712130 "Zoos and Botanical Gardens"
                , NAIC 712190 "Nature Parks and Other Similar Institutions"
                , NAIC 713110 "Amusement and Theme Parks"
                , NAIC 713120 "Amusement Arcades"
                , NAIC 713210 "Casinos (except Casino Hotels)"
                , NAIC 713290 "Other Gambling Industries"
                , NAIC 713910 "Golf Courses and Country Clubs"
                , NAIC 713920 "Skiing Facilities"
                , NAIC 713930 "Marinas"
                , NAIC 713940 "Fitness and Recreational Sports Centers"
                , NAIC 713950 "Bowling Centers"
                , NAIC 713990 "All Other Amusement and Recreation Industries"
                , NAIC 721110 "Hotels (except Casino Hotels) and Motels"
                , NAIC 721120 "Casino Hotels"
                , NAIC 721191 "Bed-and-Breakfast Inns"
                , NAIC 721199 "All Other Traveler Accommodation"
                , NAIC 721211 "RV (Recreational Vehicle) Parks and Campgrounds"
                , NAIC 721214 "Recreational and Vacation Camps (except Campgrounds)"
                , NAIC 721310 "Rooming and Boarding Houses"
                , NAIC 722310 "Food Service Contractors"
                , NAIC 722320 "Caterers"
                , NAIC 722330 "Mobile Food Services"
                , NAIC 722410 "Drinking Places (Alcoholic Beverages)"
                , NAIC 722511 "Full-Service Restaurants"
                , NAIC 722513 "Limited-Service Restaurants"
                , NAIC 722514 "Cafeterias, Grill Buffets, and Buffets"
                , NAIC 722515 "Snack and Nonalcoholic Beverage Bars"
                , NAIC 811111 "General Automotive Repair"
                , NAIC 811112 "Automotive Exhaust System Repair"
                , NAIC 811113 "Automotive Transmission Repair"
                , NAIC 811118 "Other Automotive Mechanical and Electrical Repair and Maintenance"
                , NAIC 811121 "Automotive Body, Paint, and Interior Repair and Maintenance"
                , NAIC 811122 "Automotive Glass Replacement Shops"
                , NAIC 811191 "Automotive Oil Change and Lubrication Shops"
                , NAIC 811192 "Car Washes"
                , NAIC 811198 "All Other Automotive Repair and Maintenance"
                , NAIC 811211 "Consumer Electronics Repair and Maintenance"
                , NAIC 811212 "Computer and Office Machine Repair and Maintenance"
                , NAIC 811213 "Communication Equipment Repair and Maintenance"
                , NAIC 811219 "Other Electronic and Precision Equipment Repair and Maintenance"
                , NAIC 811310 "Commercial and Industrial Machinery and Equipment (except Automotive and Electronic) Repair and Maintenance"
                , NAIC 811411 "Home and Garden Equipment Repair and Maintenance"
                , NAIC 811412 "Appliance Repair and Maintenance"
                , NAIC 811420 "Reupholstery and Furniture Repair"
                , NAIC 811430 "Footwear and Leather Goods Repair"
                , NAIC 811490 "Other Personal and Household Goods Repair and Maintenance"
                , NAIC 812111 "Barber Shops"
                , NAIC 812112 "Beauty Salons"
                , NAIC 812113 "Nail Salons"
                , NAIC 812191 "Diet and Weight Reducing Centers"
                , NAIC 812199 "Other Personal Care Services"
                , NAIC 812210 "Funeral Homes and Funeral Services"
                , NAIC 812220 "Cemeteries and Crematories"
                , NAIC 812310 "Coin-Operated Laundries and Drycleaners"
                , NAIC 812320 "Drycleaning and Laundry Services (except Coin-Operated)"
                , NAIC 812331 "Linen Supply"
                , NAIC 812332 "Industrial Launderers"
                , NAIC 812910 "Pet Care (except Veterinary) Services"
                , NAIC 812921 "Photofinishing Laboratories (except One-Hour)"
                , NAIC 812922 "One-Hour Photofinishing"
                , NAIC 812930 "Parking Lots and Garages"
                , NAIC 812990 "All Other Personal Services"
                , NAIC 813110 "Religious Organizations"
                , NAIC 813211 "Grantmaking Foundations"
                , NAIC 813212 "Voluntary Health Organizations"
                , NAIC 813219 "Other Grantmaking and Giving Services"
                , NAIC 813311 "Human Rights Organizations"
                , NAIC 813312 "Environment, Conservation and Wildlife Organizations"
                , NAIC 813319 "Other Social Advocacy Organizations"
                , NAIC 813410 "Civic and Social Organizations"
                , NAIC 813910 "Business Associations"
                , NAIC 813920 "Professional Organizations"
                , NAIC 813930 "Labor Unions and Similar Labor Organizations"
                , NAIC 813940 "Political Organizations"
                , NAIC 813990 "Other Similar Organizations (except Business, Professional, Labor, and Political Organizations)"
                , NAIC 814110 "Private Households"
                , NAIC 921110 "Executive Offices"
                , NAIC 921120 "Legislative Bodies"
                , NAIC 921130 "Public Finance Activities"
                , NAIC 921140 "Executive and Legislative Offices, Combined"
                , NAIC 921150 "American Indian and Alaska Native Tribal Governments"
                , NAIC 921190 "Other General Government Support"
                , NAIC 922110 "Courts"
                , NAIC 922120 "Police Protection"
                , NAIC 922130 "Legal Counsel and Prosecution"
                , NAIC 922140 "Correctional Institutions"
                , NAIC 922150 "Parole Offices and Probation Offices"
                , NAIC 922160 "Fire Protection"
                , NAIC 922190 "Other Justice, Public Order, and Safety Activities"
                , NAIC 923110 "Administration of Education Programs"
                , NAIC 923120 "Administration of Public Health Programs"
                , NAIC 923130 "Administration of Human Resource Programs (except Education, Public Health, and Veterans’ Affairs Programs)"
                , NAIC 923140 "Administration of Veterans’ Affairs"
                , NAIC 924110 "Administration of Air and Water Resource and Solid Waste Management Programs"
                , NAIC 924120 "Administration of Conservation Programs"
                , NAIC 925110 "Administration of Housing Programs"
                , NAIC 925120 "Administration of Urban Planning and Community and Rural Development"
                , NAIC 926110 "Administration of General Economic Programs"
                , NAIC 926120 "Regulation and Administration of Transportation Programs"
                , NAIC 926130 "Regulation and Administration of Communications, Electric, Gas, and Other Utilities"
                , NAIC 926140 "Regulation of Agricultural Marketing and Commodities"
                , NAIC 926150 "Regulation, Licensing, and Inspection of Miscellaneous Commercial Sectors"
                , NAIC 927110 "Space Research and Technology"
                , NAIC 928110 "National Security"
                , NAIC 928120 "International Affairs"
                ]
